### PR TITLE
Add more translations and languages

### PR DESCRIPTION
**Pull request by Anthony-Gaudino**
- Added new translations
- Added new languages
- Changed dates list formatting
- Updated the number of included translations on README.md from 27 to 82

### CODE REVIEW

**Comment by vwochnik** [comment]
Please tell me how exactly you achieved that / where you did pull the data from and why have you changed the date formatting? I have worked some time on getting an inline array.

**Comment by Anthony-Gaudino** [comment]
I got the data from the https://github.com/grosser/i18n_data and https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale repositories.

Since the plugins had some different languages from each other, I searched on the Internet for translations (dates only); and for the missing languages, I used English. I also looked at the ISO369-1 list to help me find the name of languages in English and in it's own language.

I used this list format for dates because it looks much more clean when reading and editing, also, this is  the format used on the https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

I did many changes manually to remove some extra information from the languages list that I think were not suitable for the plugin.

There's lots of strings that are not translated (default to English) or may be incorrect, specially on the translated languages list, and users must contribute with fixes/improvements.

**Comment by vwochnik** [comment]
> There's lots of strings that are not translated (default to English) or may be incorrect, specially on the translated languages list, and users must contribute with fixes/improvements.

Well, this is exactly why I have written a script that imports the data from two packages and only uses an intersection of languages that actually have all data completed.

Or are you implying that the language data I have generated was flawed from the beginning?

**Comment by Anthony-Gaudino** [comment]
The data you had seemed to be almost complete, but I can't guarantee that it was complete or accurate as I don't know all languages and then I can't check if everything is accurate. 

What I can do is also look for translations of languages and add them to the languages list, but note that I can't guarantee that they will be accurate, only someone that speaks the language can.

In the documentation, you should inform the users that the translations may be inaccurate or missing (default to English).
If a user finds an issue with the language he/she should provide the fix by creating an issue or a pull request.

**Comment by vwochnik** [comment]
That is exactly why I have mentioned in issue #6 that I will not include incomplete translations. IMO the set of languages that is supported for now is enough provided that the quality of the languages is good and as far as I can tell there is nothing defaulted to English.

**Comment by vwochnik** [comment]
I'm just mentioning grosser/i18n_data#12 because I have looked at the data more intensively.

**Pull request closed without merging**
